Repository kijk2869/discodo, pull requests merged in 2020-10, with the labels that each got.

#64 feat(framework): change web framework from fastapi to sanic
  discodo/__main__.py
  discodo/server/planner.py
  discodo/server/server.py
  discodo/server/websocket.py
  discodo/source/AudioData.py
  docs/server/setup.md
  requirements.txt
Labels: dependencies, documentation, enhancement, python

#65 docs(connection): edit typo
  docs/server/connection.md
Labels: documentation

#75 Added BaseUrls
  docs/server/README.md
Labels: documentation, enhancement

#77 fix: #76
  discodo/config.py
Labels: documentation, enhancement, python

#81 Added dockerfile & example config file
  Dockerfile
  example/remote/config.inc.json
Labels: dependencies, enhancement
