Repository kijk2869/discodo, pull requests merged in 2021-01, with the labels that each got.

#105 Fix some bugs
  discodo/__init__.py
  discodo/__main__.py
  discodo/client/http.py
  discodo/client/voice_client.py
  discodo/config.py
  discodo/connector.py
  discodo/errors.py
  discodo/gateway.py
  discodo/natives/__init__.py
  discodo/natives/encrypt.py
  discodo/planner.py
  discodo/player.py
  discodo/server/payloads.py
  discodo/server/restful.py
  discodo/voice_client.py
  requirements.txt
Labels: bug, enhancement, python

#123 Fix issue #121
  discodo/voice_client.py
Labels: bug, python

#129 feat: context
  discodo/client/http.py
  discodo/client/node.py
  discodo/client/voice_client.py
  discodo/manager.py
  discodo/server/payloads.py
  discodo/server/restful.py
  discodo/voice_client.py
Labels: enhancement, python
